# Generated by Django 4.1 on 2023-11-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_alter_redactor_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='content',
            field=models.TextField(),
        ),
    ]
